sudo: required
services:
    - docker

script:
    - docker-compose build
    - docker images

before_deploy:
    - docker login -u wuangyalin -p e5bf7f03-377e-4c06-a64a-3e55ba43f58a
    - docker tag personal_website_react_frontend:latest frontend:latest
    - docker tag personal_website_react_backend:latest backend:latest

deploy:
    provider: script
    script: 
        - docker push wuangyalin/frontend:latest
        - docker push wuangyalin/backend:latest
    on:
        branch: master
