sudo: required
services:
    - docker

script:
    - docker-compose build
    - docker images

before_deploy:
    - docker login -u wuangyalin -p e5bf7f03-377e-4c06-a64a-3e55ba43f58a

deploy:
    provider: script
    script: 
        - docker tag frontend luke/frontend:v1.0
        - docker tag backend luke/backend:v1.0
        - docker push luke/frontend:v1.0
        - docker push luke/backend:v1.0
    on:
        branch: master
