sudo: required
services:
    - docker

script:
    - docker-compose build
    - docker images

before_deploy:
    - docker login -u wuangyalin -p e5bf7f03-377e-4c06-a64a-3e55ba43f58a
    - docker tag frontend wuangyalin/frontend:v1.0

deploy:
    provider: script
    script: 
        - docker push wuangyalin/frontend
    on:
        branch: master
