version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ls -l
      - pwd
      - $(aws ecr get-login --region ap-southeast-2 --no-include-email)
    #   - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 087426290981.dkr.ecr.ap-southeast-2.amazonaws.com
      - REPOSITORY_URI=087426290981.dkr.ecr.ap-southeast-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build
      - docker images
      - docker tag frontend:latest $REPOSITORY_URI/react_personal_frontend:v1.0
      - docker tag backend:latest $REPOSITORY_URI/react_personal_backend:v1.0
      - docker tag mongoseed:latest $REPOSITORY_URI/react_personal_mongoseed:v1.0

    #   - docker build -t $REPOSITORY_URI:latest .
    #   - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI/react_personal_frontend
      - docker push $REPOSITORY_URI/react_personal_backend
      - docker push $REPOSITORY_URI/react_personal_mongoseed
