version: "3"
services: 
  backend:
    container_name: backend
    restart: always
    build: ./backend
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    image: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    links:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - /data:/data/dbI
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    image: mongoseed
    depends_on: 
      - mongo
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf